# Generated by Django 6.0.7 on 2026-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
